### ISSUE TITLE
Krit.: Mailadressen werden beim Feedback-Formular nicht übermittelt

### ISSUE THREAD

**Issue by lukasniebler** [RRZE-Webteam/rrze-tos#101]
Aus Helpdesk: http://go.fau.de/9rwzv

Mail-Adressen werden beim Feedback-Formular für Barrierefreiheit nicht an den Empfänger übermittelt.

Fehler konnte nachgestellt werden auf beta.wordpress.rrze.fau.de
Erhaltene Mail enthielt keine E-Mail-Adresse, obwohl beim Versand angegeben:
Erhaltene Mail im Helpdesk unter:
http://go.fau.de/9rw0e

**Comment by xwolfde** [comment]
im update
