### ISSUE TITLE
Falsche Übersetzung Impressum

### ISSUE THREAD

**Issue by TFWebm** [RRZE-Webteam/rrze-tos#112]
Mir wurde von mehreren Muttersprachlern zugetragen, dass die Übersetzung **Imprint** für Impressung falsch sei und die korrekte(re) Version **Legal Notice** lautet. Das Problem scheint zu sein, dass es kein konkretes Pendant dazu im englischsprachigen Raum zu geben scheint, siehe z. B. hier: https://www.orange-raven.de/impressumspflicht-in-den-usa-und-bei-den-vereinten-nationen/

Auch in Wörterbüchern findet sich imprint nur in Verbindung mit Drucksachen.

**Comment by xwolfde** [comment]
Das ist korrekt. Wir haben diese Übersetzung mit der Juristen-Ecke abgestimmt: Genau aus dem Grund, weil es kein  konkretes Pendant gibt und es ein rein juristischen Text ist, wurde hier die korrekte Muttersprachliche Lösung nicht genommen.
Böse gesagt: Zielgruppe der Rechtstexte, insbes. Impressum und Datenschutz, sind Juristen und nicht Muttersprachler.
Nur die Barrierefreiheitserklärung wendet sich auch an normale Nutzer.
