### ISSUE TITLE
Impressum / Optionale Angaben / zusätzlicher Abschnitt

### ISSUE THREAD

**Issue by rvdforst** [RRZE-Webteam/rrze-tos#65]
Vorschlag: Die Position des zusätzlichen Abschnitts auf dem Impressum kann bei Bedarf einstellbar sein.

**Comment by mduven** [comment]
Uns hier am Fachbereich wäre wohl sogar schon geholfen, wenn die Position nicht einstellbar ist, sondern einfach weiter nach unten rutscht. Wir fügen nur einen extra Absatz für Bildrechte ein, der so irgendwie komisch platziert ist. Wäre es u.U. praktikabel, wenn das Feld gefüllt wird ein Accordion mit "Sonstiges" o.Ä. unten anzufügen?

![2019-08-27 14_10_20-Rechts- und Wirtschaftswissenschaftliche Fakultät](https://user-images.githubusercontent.com/28564104/63770147-c974ae80-c8d4-11e9-94a6-db420d645fad.png)

**Comment by xwolfde** [comment]
Ok, wir bauen dazu in der nächsten Version was ein.

Rückfrage zu eurer Form:
Ist der Text , den ihr da nutzt, rechtlich abgesichert und abgeklärt? Sprich: Liegen die Bildrechte wirklich bei euch und nicht bei der FAU?
Außerdem weiß ich, dass einige Lizenzen aktive Links verlangen oder gar die Form der Links vorgeben, an die man sich dann auch halten muss. Ich hab da etwas Zweifel, ob die Liste die ihr da so in dem Absatz angibt, reicht.
