### ISSUE TITLE
Möglicher Barrierefreiheit Fehler auf Datenschutzseite

### ISSUE THREAD

**Issue by AndiWebred** [RRZE-Webteam/rrze-tos#97]
Siteimprove zeigt einen Accessibility-Fehler für die Datenschutzseite an: Element-IDs sind nicht eindeutig, weil es zwei Buttons mit "Opt out" gibt. Einer ist im Bereich "Sonstiges", der andere bei "Siteimprove".

**Comment by xwolfde** [comment]
fixed, war doppelt aktiv
